export const EnvironmentData = {
  status: "success",
  message: "successfully fetching gensys genpro data",
  data: [
    {
      is_active: true,
      id: 1,
      updated_by: null,
      updated_timestamp: null,
      created_by: null,
      environment_name: "dev",
      environment_desc: "development",
      created_timestamp: null,
    },
    {
      is_active: true,
      id: 2,
      updated_by: null,
      updated_timestamp: null,
      created_by: null,
      environment_name: "test",
      environment_desc: "testing",
      created_timestamp: null,
    },
    {
      is_active: true,
      id: 3,
      updated_by: null,
      updated_timestamp: null,
      created_by: null,
      environment_name: "stage",
      environment_desc: "stage",
      created_timestamp: null,
    },
    {
      is_active: true,
      id: 4,
      updated_by: null,
      updated_timestamp: null,
      created_by: null,
      environment_name: "prod",
      environment_desc: "production",
      created_timestamp: null,
    },
  ],
};

export const RegionData = {
  status: "success",
  message: "Region details fetched successfully",
  data: [
    {
      id: 1,
      is_active: true,
      updated_by: null,
      updated_timestamp: null,
      region_name: "NORTHERN REGION",
      region_desc: "NORTHERN REGION",
      created_by: null,
      created_timestamp: null,
    },
    {
      id: 2,
      is_active: true,
      updated_by: null,
      updated_timestamp: null,
      region_name: "EASTERN REGION",
      region_desc: "EASTERN REGION",
      created_by: null,
      created_timestamp: null,
    },
  ],
};
export const CatlogData = {
  status: "success",
  message: "Catelog details fetched successfully",
  data: [
    {
      region_id: 1,
      id: 1,
      created_by: null,
      created_timestamp: "2024-07-03T19:00:38",
      is_active: true,
      catelog_name: "deltashare",
      environment_id: 1,
      updated_by: null,
      updated_timestamp: "2024-07-03T19:00:38",
    },
    {
      region_id: 1,
      id: 2,
      created_by: null,
      created_timestamp: "2024-07-03T19:00:38",
      is_active: true,
      catelog_name: "global_enterprise",
      environment_id: 1,
      updated_by: null,
      updated_timestamp: "2024-07-03T19:00:38",
    },
    {
      region_id: 1,
      id: 3,
      created_by: null,
      created_timestamp: "2024-07-03T19:00:38",
      is_active: true,
      catelog_name: "poc_dev",
      environment_id: 1,
      updated_by: null,
      updated_timestamp: "2024-07-03T19:00:38",
    },
  ],
};
export const SchemaData = {
  status: "success",
  message: "Schema details fetched successfully",
  data: [
    {
      is_active: true,
      schema_id: "87f65704-c533-41a6-8560-32a1540864f4",
      schema_name: "information_schema 1",
      updated_by: null,
      updated_timestamp: "2024-07-03T21:08:08",
      catelog_id: 6,
      id: 1,
      created_by: null,
      created_timestamp: "2024-07-03T21:08:08",
    },
    {
      is_active: true,
      schema_id: "87f65704-c533-41a6-8560-32a1540864f4",
      schema_name: "information_schema 2",
      updated_by: null,
      updated_timestamp: "2024-07-03T21:16:39",
      catelog_id: 6,
      id: 2,
      created_by: null,
      created_timestamp: "2024-07-03T21:16:39",
    },
    {
      is_active: true,
      schema_id: "87f65704-c533-41a6-8560-32a1540864f4",
      schema_name: "information_schema 3",
      updated_by: null,
      updated_timestamp: "2024-07-03T21:17:25",
      catelog_id: 6,
      id: 3,
      created_by: null,
      created_timestamp: "2024-07-03T21:17:25",
    },
  ],
};
export const TableData = {
  status: "success",
  message: "Table details fetched successfully",
  data: [
    {
      catelog_id: 6,
      id: 1,
      is_active: true,
      updated_by: null,
      updated_timestamp: "2024-07-03T21:28:20",
      table_name: "catalog_privileges",
      schema_id: 1,
      table_id: "4c327a95-fb58-44dd-9606-e88330091c39",
      created_by: null,
      created_timestamp: "2024-07-03T21:28:20",
    },
    {
      catelog_id: 6,
      id: 2,
      is_active: true,
      updated_by: null,
      updated_timestamp: "2024-07-03T21:28:20",
      table_name: "catalog_provider_share_usage",
      schema_id: 1,
      table_id: "0a8c2676-47cf-449d-b88a-294bcca31869",
      created_by: null,
      created_timestamp: "2024-07-03T21:28:20",
    },
  ],
};
export const TargetData = {
  status: "success",
  message: "Target Schema details fetched successfully",
  data: [
    {
      type: "gensys",
      catelog_name: "deltashare",
      is_active: true,
      updated_by: null,
      updated_timestamp: null,
      schema_name: "information",
      id: 1,
      created_by: null,
      created_timestamp: null,
    },
    {
      type: "genpro",
      catelog_name: "global_enterprise",
      is_active: true,
      updated_by: null,
      updated_timestamp: null,
      schema_name: "default",
      id: 2,
      created_by: null,
      created_timestamp: null,
    },
  ],
};
